import os
import re

filepath = '/Users/atcharapornn/Desktop/Projest/manage.html'
with open(filepath, 'r') as f:
    content = f.read()

# Add ID to detail-code
content = re.sub(
    r'<input type="text" class="w-1/2 border border-gray-300 p-1 bg-white outline-none" value="PD-00007">',
    r'<input type="text" id="detail-code" class="w-1/2 border border-gray-300 p-1 bg-white outline-none" value="PD-00007">',
    content
)

# Add ID to detail-name
content = re.sub(
    r'<input type="text" class="w-3/4 border border-gray-300 p-1 bg-white outline-none" value="ACCUPRIL 20มก. 14\'S">',
    r'<input type="text" id="detail-name" class="w-3/4 border border-gray-300 p-1 bg-white outline-none" value="Vincristine 1mg">',
    content
)

# Add the JS function at the end.
script = """
    <script>
        function selectDrug(row, code, name) {
            // Remove active class from all rows
            const rows = document.querySelectorAll('#drug-list-body tr');
            rows.forEach(r => {
                r.className = 'hover:bg-blue-50 cursor-pointer text-gray-800';
            });
            
            // Add active class to clicked row
            row.className = 'bg-blue-600 text-white cursor-pointer hover:bg-blue-700';
            
            // Update details
            const detailCode = document.getElementById('detail-code');
            const detailName = document.getElementById('detail-name');
            if (detailCode) detailCode.value = code;
            if (detailName) detailName.value = name;
            
            // Generate mock expiry and lot data for selected drug
            const lotTbody = document.getElementById('lot-list-body');
            if (lotTbody) {
                lotTbody.innerHTML = `
                    <tr class="hover:bg-gray-50 transition-colors">
                        <td class="py-4 px-2 font-medium whitespace-nowrap">${name}</td>
                        <td class="py-4 px-2 whitespace-nowrap">LOT2026_${code}</td>
                        <td class="py-4 px-2">
                            <span class="border border-blue-400 text-blue-600 px-3 py-0.5 rounded-full text-xs font-bold whitespace-nowrap">ซื้อ</span>
                        </td>
                        <td class="py-4 px-2 whitespace-nowrap">2026-12-31</td>
                        <td class="py-4 px-2 text-center whitespace-nowrap">50 ขวด</td>
                        <td class="py-4 px-2 text-blue-700">สั่งซื้อจากบริษัท ${code}</td>
                        <td class="py-4 px-2 whitespace-nowrap">
                            <span class="inline-block bg-gray-100 text-gray-600 px-3 py-1 rounded-md text-xs font-bold whitespace-nowrap">ปกติ</span>
                        </td>
                    </tr>
                `;
            }

            const expiryTbody = document.getElementById('expiry-list-body');
            if (expiryTbody) {
                expiryTbody.innerHTML = `
                    <tr class="hover:bg-gray-50 transition-colors">
                        <td class="py-4 px-2 font-medium">${name}</td>
                        <td class="py-4 px-2">LOT2026_${code}</td>
                        <td class="py-4 px-2">31/12/2026</td>
                        <td class="py-4 px-2 text-center">50</td>
                        <td class="py-4 px-2">
                            <span class="flex items-center text-green-600 font-bold">
                                <span class="mr-1.5 border border-green-600 rounded-full w-5 h-5 flex items-center justify-center text-[10px]">✓</span> OK
                            </span>
                        </td>
                        <td class="py-4 px-2 text-gray-600">เภสัชกร สมมุติ</td>
                    </tr>
                `;
            }
        }
    </script>
</body>
"""

content = content.replace("</body>\n</html>", script + "\n</html>")

# Add onclick to the drug list
def replace_row(m):
    cls = m.group(1)
    code = m.group(2)
    name = m.group(3)
    # properly escape quotes
    safe_name = name.replace("'", "\\'")
    return f'<tr class="{cls}" onclick="selectDrug(this, \'{code}\', \'{safe_name}\')">\n                                <td class="p-1 border-r border-gray-300 pl-2">{code}</td>\n                                <td class="p-1 pl-2">{name}</td>\n                            </tr>'

# The regex matches the tr and td generated by my previous script
content = re.sub(
    r'<tr class="(.*?)">\n\s*<td class="p-1 border-r border-gray-300 pl-2">(.*?)</td>\n\s*<td class="p-1 pl-2">(.*?)</td>\n\s*</tr>',
    replace_row,
    content
)

# Add id to the drug list tbody
content = re.sub(
    r'<tbody class="divide-y divide-gray-200">',
    r'<tbody id="drug-list-body" class="divide-y divide-gray-200">',
    content,
    count=1
)

# Add id to the lot table tbody (the first divide-gray-100)
content = re.sub(
    r'<tbody class="divide-y divide-gray-100">',
    r'<tbody id="lot-list-body" class="divide-y divide-gray-100">',
    content,
    count=1
)

# Add id to the expiry table tbody (the second divide-gray-100)
content = re.sub(
    r'<tbody class="divide-y divide-gray-100">',
    r'<tbody id="expiry-list-body" class="divide-y divide-gray-100">',
    content,
    count=1
)

with open(filepath, 'w') as f:
    f.write(content)
print("Done")
